title: Ju4
email: contact@ju4.fr
description: >-
  Un petit site pour héberger quelques projets divers et variés.
baseurl: "/"
url: "https://ju4.github.io"

collections:
  readings:

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag