title: Ju4
email: contact@ju4.fr
description: >-
  Un petit site pour héberger quelques projets divers et variés.
baseurl: "/"
url: "https://ju4.fr"

collections:
  readings:
  actions:
    output: true

defaults:
  - scope:
      path: ""
      type: "actions"
    values:
      layout: "action"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag